### ISSUE TITLE
Error: Failed to parse inline template: can't convert Fixnum into String at /etc/puppet/modules/nginxpack/manifests/php/cgi.pp:172 on node localhost

### ISSUE THREAD

**Issue by rrezel** [jvaubourg/puppetlabs-nginxpack#17]
Changing :

 `line    => inline_template('post_max_size = <%= \
        (@upload_max_files.to_i * @upload_max_filesize[0..-2].to_i).to_s\
        + @upload_max_filesize[-1]%>'),`

to

 `line    => inline_template('post_max_size = <%= \
        (@upload_max_files.to_i * @upload_max_filesize[0..-2].to_i).to_s\
        + @upload_max_filesize[-1].to_s %>'),`

seems to fix it.

**Comment by sbadia** [comment]
@rrezel Thanks for this bugreport! Don't hesitate to submit a Pull-Request!
